controller_frequency: 10.0
controller_patience: 15.0 #3

planner_frequency: 2
planner_patience: 2.0 #5

oscillation_timeout: 3.0 #5
max_planning_retries: 7 #10
recovery_behaviour_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
  max_vel_x: 0.13 #0.6
  min_vel_x: 0.11
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  acc_lim_theta: 1.0

  min_vel_theta: 0.43 #0.38
  min_in_place_vel_theta: 0.4# 0.38
  max_vel_theta: 0.5
  escape_vel: -0.15

  # Omnidirectional configuration
  holonomic_robot: true

  max_vel_y: 0.2
  min_vel_y: 0.1

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3

  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

  # Trajectory Scoring Parameters
  meter_scoring: true

  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  prune_plan: false
  publish_cost_grid_pc: false
  dwa: true

  #Oscillation Prevention Parameters
  oscillation_reset_dist: 0.0

  sim_time: 10.0
#  sim_granularity: 0.05
#  angular_sim_granularity: 0.05
#  vx_samples: 3
#  vy_samples: 3
#  vtheta_samples: 12
#  simple_attractor: false
allow_unknown: false # try false
default_tolerance: 0.50 # A tolerance on the goal point for the planner.

NavfnROS:
  allow_unknown: false # try false
  default_tolerance: 0.50 # A tolerance on the goal point for the planner.

#local planner - we'll override this
DWAPlannerROS:
  holonomic_robot: true


  use_dwa: true

  # Robot configuration parameters
  acc_lim_x: 1 #3.0
  acc_lim_y: 1
  acc_lim_th: 1.0 #6

  max_vel_x: 2.0 #2
  min_vel_x: -2
  max_vel_y: 2.0
  min_vel_y: -2

  max_rot_vel: 0.8
  min_rot_vel: -0.8 #0.1

  cheat_factor: 2 #don't know if it does really something
  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.5
  latch_xy_goal_tolerance: true


  # # Forward Simulation Parameters
  sim_time: 1.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.02
  vx_samples: 20
  vy_samples: 20
  vth_samples: 35 #40

  # # Trajectory scoring parameters
  path_distance_bias: 42.0 # The weighting for how much the controller should stay close to the path it was given
  goal_distance_bias: 22.0 # The weighting for how much the controller should attempt to reach its local goal, also controls speed
  occdist_scale: 5.0 # The weighting for how much the controller should attempt to avoid obstacles
  forward_point_distance: 0.01 # The distance from the center point of the robot to place an additional scoring point, in meters
  stop_time_buffer: 0.5  # The amount of time that the robot must stThe absolute value of the veolicty at which to start scaling the robot's footprint, in m/sop before a collision in order for a trajectory to be considered valid in seconds
  scaling_speed: 0.5 # The absolute value of the veolicty at which to start scaling the robot's footprint, in m/s
  max_scaling_factor: 0.2 # The maximum factor to scale the robot's footprint by


TebLocalPlannerROS:

  odom_topic: odometry/filtered

    # Trajectory

  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: True
  allow_init_with_backwards_motion: False
  max_global_plan_lookahead_dist: 3.0
  feasibility_check_no_poses: 5

    # Robot

  max_vel_x: 0.4
  max_vel_y: 0.4
  max_vel_x_backwards: 0.2
  max_vel_y: 0.0
  max_vel_theta: 0.3
  acc_lim_x: 0.5
  acc_lim_theta: 0.5
  min_turning_radius: 0.0 # diff-drive robot (can turn on place!)

  footprint_model:
    type: "circular"
    radius: 0.4

      # GoalTolerance

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: False

    # Obstacles

  min_obstacle_dist: 0.25 # This value must also include our robot radius, since footprint_model is set to "point".
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.5
  obstacle_poses_affected: 30
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5

    # Optimization

  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1
  weight_kinematics_forward_drive: 1
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_dynamic_obstacle: 10 # not in use yet
  weight_adapt_factor: 2

  # Homotopy Class Planner

  enable_homotopy_class_planning: True
  enable_multithreading: True
  simple_exploration: False
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 1.0
  selection_alternative_time_cost: False

  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False
