// Generated by gencpp from file robotino_msgs/ResetOdometry.msg
// DO NOT EDIT!


#ifndef ROBOTINO_MSGS_MESSAGE_RESETODOMETRY_H
#define ROBOTINO_MSGS_MESSAGE_RESETODOMETRY_H

#include <ros/service_traits.h>


#include <robotino_msgs/ResetOdometryRequest.h>
#include <robotino_msgs/ResetOdometryResponse.h>


namespace robotino_msgs
{

struct ResetOdometry
{

typedef ResetOdometryRequest Request;
typedef ResetOdometryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetOdometry
} // namespace robotino_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotino_msgs::ResetOdometry > {
  static const char* value()
  {
    return "400210218ff66e5bce9e5be16653c0c8";
  }

  static const char* value(const ::robotino_msgs::ResetOdometry&) { return value(); }
};

template<>
struct DataType< ::robotino_msgs::ResetOdometry > {
  static const char* value()
  {
    return "robotino_msgs/ResetOdometry";
  }

  static const char* value(const ::robotino_msgs::ResetOdometry&) { return value(); }
};


// service_traits::MD5Sum< ::robotino_msgs::ResetOdometryRequest> should match 
// service_traits::MD5Sum< ::robotino_msgs::ResetOdometry > 
template<>
struct MD5Sum< ::robotino_msgs::ResetOdometryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotino_msgs::ResetOdometry >::value();
  }
  static const char* value(const ::robotino_msgs::ResetOdometryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotino_msgs::ResetOdometryRequest> should match 
// service_traits::DataType< ::robotino_msgs::ResetOdometry > 
template<>
struct DataType< ::robotino_msgs::ResetOdometryRequest>
{
  static const char* value()
  {
    return DataType< ::robotino_msgs::ResetOdometry >::value();
  }
  static const char* value(const ::robotino_msgs::ResetOdometryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotino_msgs::ResetOdometryResponse> should match 
// service_traits::MD5Sum< ::robotino_msgs::ResetOdometry > 
template<>
struct MD5Sum< ::robotino_msgs::ResetOdometryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotino_msgs::ResetOdometry >::value();
  }
  static const char* value(const ::robotino_msgs::ResetOdometryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotino_msgs::ResetOdometryResponse> should match 
// service_traits::DataType< ::robotino_msgs::ResetOdometry > 
template<>
struct DataType< ::robotino_msgs::ResetOdometryResponse>
{
  static const char* value()
  {
    return DataType< ::robotino_msgs::ResetOdometry >::value();
  }
  static const char* value(const ::robotino_msgs::ResetOdometryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTINO_MSGS_MESSAGE_RESETODOMETRY_H
